import { Banner, Category, Meal, Testimonial, Offer, SubscriptionPlan, AddOn } from '@/types';

export const banners: Banner[] = [
  {
    id: '1',
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=800&h=400&fit=crop',
    title: 'Fresh Meals Daily',
    subtitle: 'Healthy, delicious meals delivered to your door',
    actionType: 'category',
    actionValue: '1',
    isActive: true,
    sortOrder: 1,
  },
  {
    id: '2',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&h=400&fit=crop',
    title: 'Subscribe & Save 20%',
    subtitle: 'Get your first week free on any meal plan',
    actionType: 'offer',
    actionValue: '2',
    isActive: true,
    sortOrder: 2,
  },
  {
    id: '3',
    image: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800&h=400&fit=crop',
    title: 'Protein Rich Meals',
    subtitle: 'Perfect for your fitness goals',
    actionType: 'category',
    actionValue: '3',
    isActive: true,
    sortOrder: 3,
  },
  {
    id: '4',
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800&h=400&fit=crop',
    title: 'Authentic Indian Flavors',
    subtitle: 'Traditional recipes with a modern twist',
    actionType: 'category',
    actionValue: '5',
    isActive: true,
    sortOrder: 4,
  },
  {
    id: '5',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&h=400&fit=crop',
    title: 'How We Cook',
    subtitle: 'See our kitchen and cooking process',
    actionType: 'external',
    actionValue: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    isActive: true,
    sortOrder: 5,
  },
  {
    id: '6',
    image: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=800&h=400&fit=crop',
    title: 'Nutrition Guide',
    subtitle: 'Learn about healthy eating habits',
    actionType: 'external',
    actionValue: 'https://www.healthline.com/nutrition',
    isActive: true,
    sortOrder: 6,
  },
  {
    id: '7',
    image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&h=400&fit=crop',
    title: 'Fitness Tips',
    subtitle: 'Workout routines to complement your meals',
    actionType: 'external',
    actionValue: 'https://www.bodybuilding.com/exercises',
    isActive: true,
    sortOrder: 7,
  },
];

export const categories: Category[] = [
  {
    id: '1',
    name: 'Lunch',
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=200&h=200&fit=crop',
    description: 'Wholesome lunch meals',
    isActive: true,
    sortOrder: 1,
  },
  {
    id: '2',
    name: 'Dinner',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=200&h=200&fit=crop',
    description: 'Satisfying dinner options',
    isActive: true,
    sortOrder: 2,
  },
  {
    id: '3',
    name: 'Protein Meals',
    image: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=200&h=200&fit=crop',
    description: 'High protein, low carb',
    isActive: true,
    sortOrder: 3,
  },
  {
    id: '4',
    name: 'Vegan',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=200&h=200&fit=crop',
    description: 'Plant-based goodness',
    isActive: true,
    sortOrder: 4,
  },
  {
    id: '5',
    name: 'Indian',
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=200&h=200&fit=crop',
    description: 'Authentic Indian cuisine',
    isActive: true,
    sortOrder: 5,
  },
  {
    id: '6',
    name: 'Healthy',
    image: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=200&h=200&fit=crop',
    description: 'Nutritious & balanced',
    isActive: true,
    sortOrder: 6,
  },
  {
    id: '7',
    name: 'Desserts',
    image: 'https://images.unsplash.com/photo-1551024506-0bccd828d307?w=200&h=200&fit=crop',
    description: 'Sweet treats & desserts',
    isActive: true,
    sortOrder: 7,
  },
  {
    id: '8',
    name: 'Snacks',
    image: 'https://images.unsplash.com/photo-1599490659213-e2b9527bd087?w=200&h=200&fit=crop',
    description: 'Quick bites & snacks',
    isActive: true,
    sortOrder: 8,
  },
  {
    id: '9',
    name: 'Beverages',
    image: 'https://images.unsplash.com/photo-1544145945-f90425340c7e?w=200&h=200&fit=crop',
    description: 'Refreshing drinks & smoothies',
    isActive: true,
    sortOrder: 9,
  },
];



export const subscriptionPlans: SubscriptionPlan[] = [
  {
    id: '1',
    name: 'Meal Lite',
    duration: 2,
    originalPrice: 598,
    discountedPrice: 299,
    discount: 50,
    mealsPerDay: 1,
    description: 'Perfect to try our service',
    features: ['2 Days Trial', '1 Meal/Day', 'Free Delivery', 'Cancel Anytime'],
  },
  {
    id: '2',
    name: 'Basic Meal Plan',
    duration: 6,
    originalPrice: 1794,
    discountedPrice: 1499,
    discount: 16,
    mealsPerDay: 1,
    description: 'Great for getting started',
    features: ['6 Working Days', '1 Meal/Day', 'Free Delivery', 'Weekend Off'],
    popular: true,
  },
  {
    id: '3',
    name: 'Premium Meal Plan',
    duration: 15,
    originalPrice: 4485,
    discountedPrice: 3599,
    discount: 20,
    mealsPerDay: 1,
    description: 'Most popular choice',
    features: ['15 Working Days', '1 Meal/Day', 'Free Delivery', 'Weekend Off', '₹100 Wallet Cashback'],
  },
  {
    id: '4',
    name: 'Elite Meal Plan',
    duration: 26,
    originalPrice: 7774,
    discountedPrice: 5999,
    discount: 23,
    mealsPerDay: 1,
    description: 'Best value for money',
    features: ['26 Working Days', '1 Meal/Day', 'Free Delivery', 'Weekend Off', '₹200 Wallet Cashback', 'Priority Support'],
  },
];



export const addOns: AddOn[] = [
  {
    id: '1',
    name: 'Mixed Fruit Bowl',
    description: 'Fresh seasonal fruits',
    image: 'https://images.unsplash.com/photo-1546173159-315724a31696?w=200&h=200&fit=crop',
    price: 99,
    category: 'snack',
  },
  {
    id: '2',
    name: 'Buttermilk',
    description: 'Traditional spiced buttermilk',
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=200&h=200&fit=crop',
    price: 49,
    category: 'beverage',
  },
  {
    id: '3',
    name: 'Chicken Leg Piece',
    description: 'Grilled chicken leg piece',
    image: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=200&h=200&fit=crop',
    price: 129,
    category: 'extra',
  },
  {
    id: '4',
    name: 'Fresh Lime Water',
    description: 'Refreshing lime drink',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=200&h=200&fit=crop',
    price: 39,
    category: 'beverage',
  },
  {
    id: '5',
    name: 'Extra Rice',
    description: 'Additional portion of rice',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=200&h=200&fit=crop',
    price: 29,
    category: 'extra',
  },
  {
    id: '6',
    name: 'Gulab Jamun',
    description: 'Traditional Indian sweet',
    image: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=200&h=200&fit=crop',
    price: 89,
    category: 'dessert',
  },
];

export const featuredMeals: Meal[] = [
  {
    id: '1',
    name: 'Grilled Chicken Bowl',
    description: 'Tender grilled chicken with quinoa, roasted vegetables, and tahini dressing',
    images: ['https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=300&h=300&fit=crop'],
    categoryId: '3',
    price: 299,
    originalPrice: 349,
    isVeg: false,
    hasEgg: false,
    rating: 4.8,
    reviewCount: 124,
    tags: ['High Protein', 'Low Carb', 'Gluten Free'],
    nutritionInfo: {
      calories: 450,
      protein: 35,
      carbs: 25,
      fat: 18,
      fiber: 8,
    },
    ingredients: ['Chicken breast', 'Quinoa', 'Bell peppers', 'Zucchini', 'Tahini', 'Olive oil'],
    allergens: ['Sesame'],
    isActive: true,
    isFeatured: true,
    preparationTime: 25,
  },
  {
    id: '2',
    name: 'Mediterranean Salad',
    description: 'Fresh mixed greens with feta, olives, tomatoes, and olive oil dressing',
    images: ['https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=300&h=300&fit=crop'],
    categoryId: '1',
    price: 249,
    isVeg: true,
    hasEgg: false,
    rating: 4.6,
    reviewCount: 89,
    tags: ['Fresh', 'Light', 'Mediterranean'],
    nutritionInfo: {
      calories: 320,
      protein: 12,
      carbs: 15,
      fat: 24,
      fiber: 6,
    },
    ingredients: ['Mixed greens', 'Feta cheese', 'Olives', 'Cherry tomatoes', 'Cucumber', 'Olive oil'],
    allergens: ['Dairy'],
    isActive: true,
    isFeatured: true,
    preparationTime: 15,
  },
  {
    id: '3',
    name: 'Salmon Teriyaki',
    description: 'Pan-seared salmon with teriyaki glaze, steamed rice, and broccoli',
    images: ['https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=300&h=300&fit=crop'],
    categoryId: '2',
    price: 399,
    originalPrice: 449,
    isVeg: false,
    hasEgg: false,
    rating: 4.9,
    reviewCount: 156,
    tags: ['Omega-3', 'Premium', 'Japanese'],
    nutritionInfo: {
      calories: 520,
      protein: 42,
      carbs: 35,
      fat: 22,
      fiber: 4,
    },
    ingredients: ['Salmon fillet', 'Teriyaki sauce', 'Jasmine rice', 'Broccoli', 'Sesame seeds'],
    allergens: ['Fish', 'Soy', 'Sesame'],
    isActive: true,
    isFeatured: true,
    preparationTime: 30,
  },
  {
    id: '4',
    name: 'Paneer Tikka Masala',
    description: 'Creamy tomato curry with grilled paneer cubes and aromatic spices',
    images: ['https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=300&h=300&fit=crop'],
    categoryId: '2',
    price: 279,
    isVeg: true,
    hasEgg: false,
    rating: 4.7,
    reviewCount: 203,
    tags: ['Indian', 'Spicy', 'Creamy'],
    nutritionInfo: {
      calories: 420,
      protein: 18,
      carbs: 32,
      fat: 26,
      fiber: 5,
    },
    ingredients: ['Paneer', 'Tomato puree', 'Onions', 'Cream', 'Garam masala', 'Basmati rice'],
    allergens: ['Dairy'],
    isActive: true,
    isFeatured: true,
    preparationTime: 35,
  },
  {
    id: '5',
    name: 'Quinoa Buddha Bowl',
    description: 'Nutritious bowl with quinoa, roasted vegetables, avocado, and tahini',
    images: ['https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=300&h=300&fit=crop'],
    categoryId: '4',
    price: 329,
    originalPrice: 379,
    isVeg: true,
    hasEgg: false,
    rating: 4.5,
    reviewCount: 167,
    tags: ['Vegan', 'Superfood', 'Healthy'],
    nutritionInfo: {
      calories: 380,
      protein: 14,
      carbs: 45,
      fat: 16,
      fiber: 12,
    },
    ingredients: ['Quinoa', 'Avocado', 'Sweet potato', 'Chickpeas', 'Kale', 'Tahini'],
    allergens: ['Sesame'],
    isActive: true,
    isFeatured: true,
    preparationTime: 25,
  },
  {
    id: '6',
    name: 'Chicken Biryani',
    description: 'Fragrant basmati rice with tender chicken and traditional spices',
    images: ['https://images.unsplash.com/photo-1563379091339-03246963d96c?w=300&h=300&fit=crop'],
    categoryId: '1',
    price: 349,
    isVeg: false,
    hasEgg: false,
    rating: 4.8,
    reviewCount: 289,
    tags: ['Indian', 'Aromatic', 'Traditional'],
    nutritionInfo: {
      calories: 580,
      protein: 32,
      carbs: 68,
      fat: 18,
      fiber: 3,
    },
    ingredients: ['Chicken', 'Basmati rice', 'Saffron', 'Fried onions', 'Yogurt', 'Biryani masala'],
    allergens: ['Dairy'],
    isActive: true,
    isFeatured: true,
    preparationTime: 45,
  },
  // Additional meals for better filtering/sorting demonstration
  {
    id: '7',
    name: 'Vegan Protein Bowl',
    description: 'Plant-based protein with lentils, chickpeas, and hemp seeds',
    images: ['https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=300&h=300&fit=crop'],
    categoryId: '4',
    price: 189,
    isVeg: true,
    hasEgg: false,
    rating: 4.3,
    reviewCount: 78,
    tags: ['Vegan', 'High Protein', 'Gluten Free'],
    nutritionInfo: {
      calories: 420,
      protein: 28,
      carbs: 35,
      fat: 15,
      fiber: 14,
    },
    ingredients: ['Lentils', 'Chickpeas', 'Hemp seeds', 'Spinach', 'Tahini'],
    allergens: ['Sesame'],
    isActive: true,
    isFeatured: false,
    preparationTime: 20,
  },
  {
    id: '8',
    name: 'Butter Chicken',
    description: 'Rich and creamy tomato-based curry with tender chicken pieces',
    images: ['https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=300&h=300&fit=crop'],
    categoryId: '5',
    price: 459,
    originalPrice: 499,
    isVeg: false,
    hasEgg: false,
    rating: 4.9,
    reviewCount: 342,
    tags: ['Indian', 'Creamy', 'Premium'],
    nutritionInfo: {
      calories: 620,
      protein: 38,
      carbs: 42,
      fat: 32,
      fiber: 4,
    },
    ingredients: ['Chicken', 'Tomato puree', 'Butter', 'Cream', 'Spices', 'Basmati rice'],
    allergens: ['Dairy'],
    isActive: true,
    isFeatured: true,
    preparationTime: 40,
  },
  {
    id: '9',
    name: 'Greek Salad',
    description: 'Traditional Greek salad with feta, olives, and fresh vegetables',
    images: ['https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=300&h=300&fit=crop'],
    categoryId: '6',
    price: 179,
    isVeg: true,
    hasEgg: false,
    rating: 4.2,
    reviewCount: 56,
    tags: ['Fresh', 'Light', 'Mediterranean'],
    nutritionInfo: {
      calories: 280,
      protein: 8,
      carbs: 12,
      fat: 22,
      fiber: 5,
    },
    ingredients: ['Cucumber', 'Tomatoes', 'Feta cheese', 'Olives', 'Olive oil'],
    allergens: ['Dairy'],
    isActive: true,
    isFeatured: false,
    preparationTime: 10,
  },
  {
    id: '10',
    name: 'Chocolate Brownie',
    description: 'Rich, fudgy chocolate brownie with walnuts',
    images: ['https://images.unsplash.com/photo-1551024506-0bccd828d307?w=300&h=300&fit=crop'],
    categoryId: '7',
    price: 149,
    isVeg: true,
    hasEgg: true,
    rating: 4.7,
    reviewCount: 198,
    tags: ['Sweet', 'Dessert', 'Chocolate'],
    nutritionInfo: {
      calories: 380,
      protein: 6,
      carbs: 45,
      fat: 18,
      fiber: 3,
    },
    ingredients: ['Dark chocolate', 'Butter', 'Sugar', 'Eggs', 'Flour', 'Walnuts'],
    allergens: ['Eggs', 'Gluten', 'Nuts'],
    isActive: true,
    isFeatured: false,
    preparationTime: 35,
  },
  {
    id: '11',
    name: 'Protein Smoothie Bowl',
    description: 'Thick smoothie bowl topped with granola, berries, and protein powder',
    images: ['https://images.unsplash.com/photo-1511690743698-d9d85f2fbf38?w=300&h=300&fit=crop'],
    categoryId: '8',
    price: 229,
    isVeg: true,
    hasEgg: false,
    rating: 4.4,
    reviewCount: 87,
    tags: ['High Protein', 'Healthy', 'Fresh'],
    nutritionInfo: {
      calories: 350,
      protein: 25,
      carbs: 38,
      fat: 12,
      fiber: 8,
    },
    ingredients: ['Protein powder', 'Banana', 'Berries', 'Granola', 'Almond milk'],
    allergens: ['Nuts'],
    isActive: true,
    isFeatured: false,
    preparationTime: 15,
  },
  {
    id: '12',
    name: 'Dal Tadka',
    description: 'Traditional yellow lentil curry with aromatic tempering',
    images: ['https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=300&h=300&fit=crop'],
    categoryId: '5',
    price: 159,
    isVeg: true,
    hasEgg: false,
    rating: 4.1,
    reviewCount: 145,
    tags: ['Indian', 'Comfort Food', 'Protein Rich'],
    nutritionInfo: {
      calories: 280,
      protein: 18,
      carbs: 42,
      fat: 6,
      fiber: 12,
    },
    ingredients: ['Yellow lentils', 'Turmeric', 'Cumin', 'Onions', 'Tomatoes', 'Rice'],
    allergens: [],
    isActive: true,
    isFeatured: false,
    preparationTime: 30,
  },
];

export const testimonials: Testimonial[] = [
  {
    id: '1',
    userName: 'Priya Sharma',
    userImage: 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=100&h=100&fit=crop&crop=face',
    rating: 5,
    comment: 'Amazing food quality and timely delivery. The subscription has made my life so much easier!',
    isActive: true,
    createdAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    userName: 'Rahul Gupta',
    userImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face',
    rating: 5,
    comment: 'Perfect for my fitness goals. High protein meals that actually taste great!',
    isActive: true,
    createdAt: new Date('2024-01-20'),
  },
  {
    id: '3',
    userName: 'Anita Patel',
    userImage: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop&crop=face',
    rating: 4,
    comment: 'Love the variety and freshness. My family enjoys every meal!',
    isActive: true,
    createdAt: new Date('2024-01-25'),
  },
  {
    id: '4',
    userName: 'Arjun Singh',
    userImage: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face',
    rating: 5,
    comment: 'The Indian meals taste just like home. Excellent service and packaging!',
    isActive: true,
    createdAt: new Date('2024-02-01'),
  },
  {
    id: '5',
    userName: 'Sneha Reddy',
    userImage: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&h=100&fit=crop&crop=face',
    rating: 4,
    comment: 'Great vegan options! Finally found a service that caters to my dietary needs.',
    isActive: true,
    createdAt: new Date('2024-02-05'),
  },
];

export const offers: Offer[] = [
  {
    id: '1',
    title: 'First Order Free',
    description: 'Get your first meal absolutely free on any subscription',
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=200&h=120&fit=crop',
    discountType: 'percentage',
    discountValue: 100,
    promoCode: 'FIRST100',
    validFrom: new Date('2024-01-01'),
    validTo: new Date('2025-01-31'),
    isActive: true,
    usageLimit: 1000,
    usedCount: 245,
    offerType: 'discount',
    discount: '100% OFF',
    code: 'FIRST100',
    validUntil: 'Jan 31, 2025',
    longDescription: 'Welcome to our meal delivery service! Get your first meal completely free when you subscribe to any of our meal plans. This is a limited-time offer for new customers only.',
    terms: [
      'Valid for new customers only',
      'Applicable on first subscription only',
      'Cannot be combined with other offers',
      'Valid until January 31, 2025',
      'Minimum subscription of 2 days required'
    ]
  },
  {
    id: '2',
    title: 'Weekend Special',
    description: '20% off on weekend meal plans',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=200&h=120&fit=crop',
    discountType: 'percentage',
    discountValue: 20,
    promoCode: 'WEEKEND20',
    validFrom: new Date('2024-01-01'),
    validTo: new Date('2025-01-15'),
    isActive: true,
    usageLimit: 500,
    usedCount: 123,
    offerType: 'discount',
    discount: '20% OFF',
    code: 'WEEKEND20',
    validUntil: 'Jan 15, 2025',
    longDescription: 'Enjoy delicious meals on weekends with our special discount! Perfect for family gatherings and weekend treats.',
    terms: [
      'Valid on weekend orders only (Saturday & Sunday)',
      'Minimum order value ₹300',
      'Maximum discount ₹200',
      'Valid for limited time',
      'Cannot be combined with other offers'
    ]
  },
  {
    id: '3',
    title: 'Wallet Cashback',
    description: 'Get ₹100 cashback on orders above ₹500',
    image: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=200&h=120&fit=crop',
    discountType: 'cashback',
    discountValue: 100,
    minOrderAmount: 500,
    validFrom: new Date('2024-01-01'),
    validTo: new Date('2025-02-28'),
    isActive: true,
    usageLimit: 1000,
    usedCount: 67,
    offerType: 'cashback',
    discount: '₹100 Cashback',
    validUntil: 'Feb 28, 2025',
    longDescription: 'Get instant cashback in your wallet! The cashback amount will be credited to your wallet within 24 hours of order delivery and can be used for future orders.',
    terms: [
      'Minimum order value ₹500',
      'Cashback credited within 24 hours',
      'Valid for all customers',
      'Cashback expires in 90 days',
      'Can be used for future orders'
    ]
  },
  {
    id: '4',
    title: 'Protein Pack',
    description: 'Special discount on high-protein meals',
    image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=200&h=120&fit=crop',
    discountType: 'percentage',
    discountValue: 25,
    promoCode: 'PROTEIN25',
    validFrom: new Date('2024-01-01'),
    validTo: new Date('2025-02-15'),
    isActive: true,
    usageLimit: 300,
    usedCount: 89,
    offerType: 'deal',
    discount: '25% OFF',
    code: 'PROTEIN25',
    validUntil: 'Feb 15, 2025',
    longDescription: 'Perfect for fitness enthusiasts! Get amazing discounts on our high-protein meal collection. All meals contain 25g+ protein per serving.',
    terms: [
      'Valid on protein meals category only',
      'Meals contain 25g+ protein per serving',
      'Valid for subscription and one-time orders',
      'Cannot be combined with other offers',
      'Limited time offer'
    ]
  },
  {
    id: '5',
    title: 'Healthy Choice',
    description: 'Buy 2 get 1 free on vegan meals',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=200&h=120&fit=crop',
    discountType: 'percentage',
    discountValue: 33,
    promoCode: 'VEGAN3',
    validFrom: new Date('2024-01-01'),
    validTo: new Date('2025-01-20'),
    isActive: true,
    usageLimit: 200,
    usedCount: 45,
    offerType: 'deal',
    discount: 'Buy 2 Get 1 Free',
    code: 'VEGAN3',
    validUntil: 'Jan 20, 2025',
    longDescription: 'Discover the goodness of plant-based nutrition! Order any 2 vegan meals and get the 3rd one absolutely free. Perfect for trying new flavors.',
    terms: [
      'Valid on vegan meals only',
      'Buy 2 meals, get 1 free (lowest priced)',
      'Valid for one-time orders only',
      'Cannot be combined with other offers',
      'Free meal will be the lowest priced one'
    ]
  },
  {
    id: '6',
    title: 'Student Special',
    description: 'Exclusive 30% discount for students',
    image: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=200&h=120&fit=crop',
    discountType: 'percentage',
    discountValue: 30,
    promoCode: 'STUDENT30',
    validFrom: new Date('2024-01-01'),
    validTo: new Date('2025-12-31'),
    isActive: true,
    usageLimit: 1000,
    usedCount: 156,
    offerType: 'discount',
    discount: '30% OFF',
    code: 'STUDENT30',
    validUntil: 'Dec 31, 2025',
    longDescription: 'Special discount for students! Show your student ID and get 30% off on all meal plans. Perfect for budget-conscious students who want healthy meals.',
    terms: [
      'Valid student ID required',
      'Valid for students aged 18-25',
      'Applicable on all meal plans',
      'Maximum discount ₹300 per order',
      'Verification required for first use'
    ]
  }
];

// Storage for subscriptions
export let userSubscriptions: any[] = [];

// Wallet transactions for cashback tracking
export let walletTransactions: any[] = [];

export const addSubscription = (subscription: any) => {
  userSubscriptions.push({
    ...subscription,
    id: Date.now().toString(),
    createdAt: new Date(),
  });
};

export const getUserSubscriptions = (userId: string) => {
  return userSubscriptions.filter(sub => sub.userId === userId);
};

// Delivery time slots
export const deliveryTimeSlots = [
  { id: '1', time: '12:00 PM - 1:00 PM', label: 'Lunch Time' },
  { id: '2', time: '1:00 PM - 2:00 PM', label: 'Afternoon' },
  { id: '3', time: '7:00 PM - 8:00 PM', label: 'Dinner Time' },
  { id: '4', time: '8:00 PM - 9:00 PM', label: 'Late Dinner' },
];

// Promotional Section Data (Admin Controllable)
export interface PromotionalItem {
  id: string;
  title: string;
  subtitle?: string;
  image: string;
  backgroundColor: string;
  textColor: string;
  icon?: string;
  actionType: 'category' | 'offer' | 'external' | 'meal';
  actionValue: string;
  size: 'large' | 'medium' | 'small';
  position: number;
  isActive: boolean;
}

export const promotionalSections = {
  // Festival/Event Section (like Vinayaka Chavithi in the image)
  festival: {
    title: 'Celebrate Vinayaka Chavithi',
    backgroundColor: '#FFF8E1', // Light yellow background
    items: [
      {
        id: 'festival-main',
        title: 'Get a FREE Laddu Box',
        subtitle: 'on orders above ₹999',
        image: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=200&h=200&fit=crop',
        backgroundColor: '#FF8F00',
        textColor: '#FFFFFF',
        icon: 'gift',
        actionType: 'offer' as const,
        actionValue: 'LADDU999',
        size: 'large' as const,
        position: 1,
        isActive: true,
      },
      {
        id: 'festival-1',
        title: 'Idols & Pooja Needs',
        image: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=200&h=200&fit=crop',
        backgroundColor: '#FFA726',
        textColor: '#FFFFFF',
        actionType: 'category' as const,
        actionValue: 'pooja',
        size: 'medium' as const,
        position: 2,
        isActive: true,
      },
      {
        id: 'festival-2',
        title: 'Festive Get-Togethers',
        image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=200&h=200&fit=crop',
        backgroundColor: '#FF7043',
        textColor: '#FFFFFF',
        actionType: 'category' as const,
        actionValue: 'party-meals',
        size: 'medium' as const,
        position: 3,
        isActive: true,
      },
      {
        id: 'festival-3',
        title: 'Modak & Sweets',
        image: 'https://images.unsplash.com/photo-1551024506-0bccd828d307?w=200&h=200&fit=crop',
        backgroundColor: '#8BC34A',
        textColor: '#FFFFFF',
        actionType: 'category' as const,
        actionValue: 'sweets',
        size: 'small' as const,
        position: 4,
        isActive: true,
      },
      {
        id: 'festival-4',
        title: 'Home Decor',
        image: 'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=200&h=200&fit=crop',
        backgroundColor: '#9C27B0',
        textColor: '#FFFFFF',
        actionType: 'category' as const,
        actionValue: 'decor',
        size: 'small' as const,
        position: 5,
        isActive: true,
      },
      {
        id: 'festival-5',
        title: 'Festive Ready',
        image: 'https://images.unsplash.com/photo-1544441893-675973e31985?w=200&h=200&fit=crop',
        backgroundColor: '#E91E63',
        textColor: '#FFFFFF',
        actionType: 'category' as const,
        actionValue: 'ready-meals',
        size: 'small' as const,
        position: 6,
        isActive: true,
      },
      {
        id: 'festival-6',
        title: 'Festival Recipes',
        image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=200&h=200&fit=crop',
        backgroundColor: '#673AB7',
        textColor: '#FFFFFF',
        actionType: 'external' as const,
        actionValue: 'https://www.indianhealthyrecipes.com/recipes/festival-recipes/',
        size: 'small' as const,
        position: 7,
        isActive: true,
      },
    ],
  },
  // Regular promotional section (can be changed by admin)
  weekly: {
    title: 'This Week\'s Special',
    backgroundColor: '#E8F5E8',
    items: [
      {
        id: 'weekly-main',
        title: 'Healthy Meal Plans',
        subtitle: 'Starting from ₹199/day',
        image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=200&h=200&fit=crop',
        backgroundColor: '#4CAF50',
        textColor: '#FFFFFF',
        icon: 'star',
        actionType: 'offer' as const,
        actionValue: 'HEALTHY199',
        size: 'large' as const,
        position: 1,
        isActive: true,
      },
      {
        id: 'weekly-1',
        title: 'Protein Power',
        image: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=200&h=200&fit=crop',
        backgroundColor: '#FF5722',
        textColor: '#FFFFFF',
        actionType: 'category' as const,
        actionValue: '3',
        size: 'medium' as const,
        position: 2,
        isActive: true,
      },
      {
        id: 'weekly-2',
        title: 'Quick Delivery',
        image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=200&h=200&fit=crop',
        backgroundColor: '#2196F3',
        textColor: '#FFFFFF',
        actionType: 'offer' as const,
        actionValue: 'QUICK30',
        size: 'medium' as const,
        position: 3,
        isActive: true,
      },
      {
        id: 'weekly-3',
        title: 'Vegan',
        image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=200&h=200&fit=crop',
        backgroundColor: '#8BC34A',
        textColor: '#FFFFFF',
        actionType: 'category' as const,
        actionValue: '4',
        size: 'small' as const,
        position: 4,
        isActive: true,
      },
      {
        id: 'weekly-4',
        title: 'Indian',
        image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=200&h=200&fit=crop',
        backgroundColor: '#FF9800',
        textColor: '#FFFFFF',
        actionType: 'category' as const,
        actionValue: '5',
        size: 'small' as const,
        position: 5,
        isActive: true,
      },
      {
        id: 'weekly-5',
        title: 'Desserts',
        image: 'https://images.unsplash.com/photo-1551024506-0bccd828d307?w=200&h=200&fit=crop',
        backgroundColor: '#E91E63',
        textColor: '#FFFFFF',
        actionType: 'category' as const,
        actionValue: '7',
        size: 'small' as const,
        position: 6,
        isActive: true,
      },
    ],
  },
};

// Function to get active promotional section (admin can control which one to show)
export const getActivePromotionalSection = () => {
  // Admin can change this to show different sections
  // For now, showing festival section
  return promotionalSections.festival;
};